# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='updated',
        ),
        migrations.AddField(
            model_name='story',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign'),
        ),
        migrations.AddField(
            model_name='story',
            name='posted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='ingamedate',
            field=models.DateField(),
        ),
    ]
