# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('char_class', models.CharField(max_length=100)),
                ('exp', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('photo_full', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('ingamedate', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='genre',
        ),
        migrations.AddField(
            model_name='campaign',
            name='camp_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rp_system',
            field=models.CharField(choices=[('no', 'None'), ('gp', 'GURPS'), ('d5e', 'DnD 5e')], default='None', max_length=5, verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(verbose_name='Описание кампании'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='ended',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='started',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название кампании'),
        ),
    ]
