# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20161207_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='camp_slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
