# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20161207_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='camp_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
