# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20161207_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='camp_slug',
            field=models.SlugField(default=''),
        ),
    ]
