# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20170111_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ended',
            field=models.DateField(auto_now_add=True, verbose_name='Последняя история'),
        ),
        migrations.AlterField(
            model_name='story',
            name='ingamedate',
            field=models.DateField(help_text='Формат ГГГГ-ММ-ДД', verbose_name='Внутриигровая дата'),
        ),
    ]
