# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20161208_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='camp_slug',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='rp_system',
            field=models.CharField(choices=[('no', 'None'), ('gp', 'GURPS'), ('d5e', 'DnD 5e')], default='no', max_length=5, verbose_name='Система'),
        ),
    ]
