# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaignmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmap',
            name='file',
            field=models.ImageField(blank=True, height_field=models.IntegerField(blank=True), upload_to='maps/', width_field=models.IntegerField(blank=True)),
        ),
        migrations.AlterField(
            model_name='campaignmap',
            name='img_height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaignmap',
            name='img_width',
            field=models.IntegerField(blank=True),
        ),
    ]
