# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_achievment'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievment',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='achievments_img/'),
        ),
        migrations.AddField(
            model_name='achievment',
            name='owners',
            field=models.ManyToManyField(to='campaign.Character'),
        ),
    ]
