# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_auto_20170116_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmap',
            name='file',
            field=models.ImageField(blank=True, height_field='img_height', upload_to='maps/', width_field='img_width'),
        ),
    ]
