# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('img', models.FileField(blank=True, null=True, upload_to='achievments_img/')),
                ('owners', models.ManyToManyField(to='character.Character')),
            ],
        ),
    ]
