# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolders', '0002_auto_20161123_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('char_class', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
