# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolders', '0003_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
