# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('char_class', models.CharField(max_length=100)),
                ('exp', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('photo_full', models.FileField(blank=True, null=True, upload_to='')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
