# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='private_stats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='public_stats',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
