# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20170109_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='masters_notes',
            field=models.TextField(blank=True),
        ),
    ]
